### ISSUE TITLE
Please clarify the system requirements

### ISSUE THREAD

**Issue by tempelmann** [firecore/InfuseSync#17]
Jellyfin works on many platforms, including Linux and macOS.
This plugin, however, seems to work only on Windows, it seems.
Or do I have this wrong?
Would you please add some details to the Readme to avoid confusion.

Actually, now I realiize that it's not a plugin that goes into Jellybin but into Infuse. That's even more confusing because I'm running Infuse on iOS (more exactly on an AppleTV). There's no way to install plugins there, especially not a .dll.

So, in any way, it would be nice if you'd make that clearer.

**Comment by Corey-Evans** [comment]
It's an Jellyfin/Emby plugin, not an Infuse plugin. 

The instructions on the readme are for building the plugin from the source code.

You should be able to take the *.dll file from the latest release (https://github.com/firecore/InfuseSync/releases) and put it in the relevant location on your Jellyfin/Emby server.

It's a dll file because Jellyfin is a .NET program. It should work on an system Jellyfin has been compiled for, as the program will be using the dll file, not the OS.

**Comment by anthonylavado** [comment]
To top it all off - the plugin is available in our official plugin repository, so you don't even have to add it manually. It should be automatically installed when you connect Infuse to your server, or you can install it from inside Jellyfin.
